# Generated by Django 5.1.3 on 2024-11-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_addressed',
            field=models.BooleanField(default=False),
        ),
    ]
